[package]
org = "ballerina"
name = "tool_scan"
version = "0.1.0"
distribution = "2201.9.1"
authors = ["Ballerina"]
keywords = ["scan", "static code analysis"]
license = ["Apache-2.0"]
repository = "https://github.com/ballerina-platform/static-code-analysis-tool"
